<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2023-04-11 21:26:06
 */
return [
    'all' => [
        'class' => 'frontend\\assets\\AppAsset',
        'basePath' => '@webroot/',
        'baseUrl' => '@web/',
        'js' => [
            'js/all.min.js',
        ],
        'css' => [
            'css/all.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'frontend\\assets\\AppAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
];